[package]
name = "snowflake-bounce"
version = "0.1.0"
edition = "2024"
authors = ["T.Sawyer <saylesss87@proton.me>"]
description = "A bouncing NixOS snowflake screensaver"
license = "GPL-3.0-or-later"
repository = "https://github.com/saylesss88/snowflake-bounce"

[dependencies]
pancurses = {version = "0.17", features = ["wide"]}
rand = {version = "0.8.5", features = ["small_rng"]}

# rand = {version = "0.9.2", features = ["small_rng"]}
signal-hook = "0.4.1"
term_size = "0.3"
libc = "0.2"
